# git-cliff configuration.
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project are documented here.
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
# Group commits by the same conventional-commit types used in this repository.
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^doc", group = "<!-- 2 -->Documentation" },
  { message = "^refactor", group = "<!-- 3 -->Refactor" },
  { message = "^test", group = "<!-- 4 -->Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore", group = "<!-- 5 -->Chores" },
  { message = ".*", group = "<!-- 6 -->Other" },
]
filter_commits = false
sort_commits = "oldest"
